name: xeus-octave
channels:
  - conda-forge
dependencies:
  # Workaround
  - xeus-octave
  - octave_kernel
  # For Plotly graphical toolkit
  - plotly
  # Runtime dependency for Octave ``symbolic`` package.
  - sympy
  # For compiling the Octave ``control`` and ``signal`` packages
  #- compilers
  #- make