name: xeus-octave
channels:
- conda-forge
dependencies:
- xeus-octave
- octave
- octave_kernel
- nodejs
- texinfo
- gnuplot
# For Plotly graphical toolkit
- plotly
# Runtime dependency for Octave ``symbolic`` package.
- sympy
# For compiling the Octave ``control`` and ``signal`` packages
- compilers
- make
# for fltk graphictoolkit option
- fltk
# for qt graphictoolkit option
- qt
- ipywidgets  
